### ISSUE TITLE
Implement edge weights

### ISSUE THREAD

**Issue by DanielSeemaier** [KarlsruheGraphGeneration/KaGen#30]
It would be nice to have an option for edge weights based on the distance between adjacent vertices.

**Comment by lCavendishl** [comment]
Here are the remaining tasks for edge weights:

-     Randomized edge weights are unfinished. Corresponding edges need to be sorted for binary search 
-     Restructuring how coordinates are handled is necessary to ensure that all required coordinates are available later for weight calculation based on distance
-     The weights need to be written into the output file
