### ISSUE TITLE
Move KaGen into a Github Orga?

### ISSUE THREAD

**Issue by schulzchristian** [KarlsruheGraphGeneration/KaGen#35]
Hi all,

should we move KaGen into a github orga?

Best
Christian

**Comment by DanielSeemaier** [comment]
@sebalamm would you be fine with that?

**Comment by sebalamm** [comment]
Sure!

2023年3月27日(月) 11:55 Daniel Seemaier ***@***.***>:

**Comment by DanielSeemaier** [comment]
Great! I've created a new orga and invited you, but I think that only you can actually move the repo
