### ISSUE TITLE
Broken Coordinate Collection in RHG generator

### ISSUE THREAD

**Issue by niklas-uhl** [KarlsruheGraphGeneration/KaGen#40]
> Also, coordinates were not collected properly, because due to the lazy cell generation, they were not collect in the right order

This might be broken for hyperbolic graphs as well then

_Originally posted by @DanielSeemaier in https://github.com/KarlsruheGraphGeneration/KaGen/issues/39#issuecomment-1702868264_

**Comment by DanielSeemaier** [comment]
Fixed in b9f2463
