### ISSUE TITLE
Draft a release

### ISSUE THREAD

**Issue by schulzchristian** [KarlsruheGraphGeneration/KaGen#41]
Hi everyone, should we draft a release and assign version numbers to the project?

Best
Christian

**Comment by DanielSeemaier** [comment]
Hey, I agree, and in fact the library header already defines the current version as 

```
#define KAGEN_VERSION_MAJOR 0
#define KAGEN_VERSION_MINOR 3
#define KAGEN_VERSION_PATCH 0
```

The binary has a `-v,--version` flag to print the version and build configuration. 

Maybe we should discuss whether we should bump the version to 1.0.0 for a first "official Github release"; arguments against that are open issues #40 and #38 and maybe one could argue that we need more rigorous testing in general, especially for smaller graphs.
